// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf3kaXkBQMHus5AiD9XH9GSYvuvUFdSGI',
    appId: '1:892927927991:web:5402fa6d466569c4030f32',
    messagingSenderId: '892927927991',
    projectId: 'carnova-app-9e042',
    authDomain: 'carnova-app-9e042.firebaseapp.com',
    storageBucket: 'carnova-app-9e042.firebasestorage.app',
    measurementId: 'G-SZHJC4EW8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRObUK71vSIJloQSXXx1BI6Hz4Jje-r4k',
    appId: '1:892927927991:android:a516c156aade0cbf030f32',
    messagingSenderId: '892927927991',
    projectId: 'carnova-app-9e042',
    storageBucket: 'carnova-app-9e042.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALQPvIrXnsmPt9x7u_R6CgnoWoup7yJJA',
    appId: '1:892927927991:ios:0de66b85cd835cec030f32',
    messagingSenderId: '892927927991',
    projectId: 'carnova-app-9e042',
    storageBucket: 'carnova-app-9e042.firebasestorage.app',
    iosBundleId: 'com.example.carnovaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALQPvIrXnsmPt9x7u_R6CgnoWoup7yJJA',
    appId: '1:892927927991:ios:0de66b85cd835cec030f32',
    messagingSenderId: '892927927991',
    projectId: 'carnova-app-9e042',
    storageBucket: 'carnova-app-9e042.firebasestorage.app',
    iosBundleId: 'com.example.carnovaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf3kaXkBQMHus5AiD9XH9GSYvuvUFdSGI',
    appId: '1:892927927991:web:f7cc568f65b7655e030f32',
    messagingSenderId: '892927927991',
    projectId: 'carnova-app-9e042',
    authDomain: 'carnova-app-9e042.firebaseapp.com',
    storageBucket: 'carnova-app-9e042.firebasestorage.app',
    measurementId: 'G-LH6ZRNRSKW',
  );
}
